PATIENT_NUMBER = 5000
DOCTOR_NUMBER = 100
NURSE_NUMBER = 200
ADMIN_NUMBER = 10
PHARMACIST_NUMBER = 10
ACCOUNTANT_NUMBER = 15
USER_NUMBER = PATIENT_NUMBER + DOCTOR_NUMBER + NURSE_NUMBER + ADMIN_NUMBER + PHARMACIST_NUMBER + ACCOUNTANT_NUMBER


