from os.path import dirname
from pathlib import Path

# WARNING! AUTO-GENERATED CONSTANTS! DO NOT CHANGE THEM!
PATH = Path(dirname(__file__))

# User-specified constants
PATIENT_NUMBER = 100
DOCTOR_NUMBER = 10
NURSE_NUMBER = 20
ADMIN_NUMBER = 10
PHARMACIST_NUMBER = 10
ACCOUNTANT_NUMBER = 15
USER_NUMBER = PATIENT_NUMBER + DOCTOR_NUMBER + NURSE_NUMBER + ADMIN_NUMBER + PHARMACIST_NUMBER + ACCOUNTANT_NUMBER
MAX_APPOINTMENT_NUMBER = 30
APPOINTMENT_NOTIFICATION_TITLE = "Upcoming appointment"
APPOINTMENT_NOTIFICATION_CONTENT = 'Do not forget that you have appointment {id} in room {room}.'
HOSPITAL_START_YEAR = 2006
START_WORKING_HOUR = 10
END_WORKING_HOUR = 18
MAX_SLOTS_PER_DAY = 32
SLOT_DURATION = (END_WORKING_HOUR - START_WORKING_HOUR) * 60 // MAX_SLOTS_PER_DAY  # == 15 minutes
MIN_ROOM_NUMBER = 100
MAX_ROOM_NUMBER = 500
START_BIRTHDATE_YEAR = 1935
END_BIRTHDATE_YEAR = HOSPITAL_START_YEAR - 1

DATASETS_FOLDER = PATH / "datasets"

ADDRESS_SET_FILE = DATASETS_FOLDER / "address.txt"
FNAME_SET_FILE = DATASETS_FOLDER / "first_names.all.txt"
LNAME_SET_FILE = DATASETS_FOLDER / "last_names.all.txt"
EMAIL_SET_FILE = DATASETS_FOLDER / "email.txt"
PHONE_SET_FILE = DATASETS_FOLDER / "phone.txt"
PASSWORD_SET_FILE = DATASETS_FOLDER / "password.txt"
